spring:
  application:
    name: thenadlee
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: "${MYSQL_URL}"
    username: "${MYSQL_USERNAME}"
    password: "${MYSQL_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
logging:
  level:
    org.hibernate.jdbc.bind: trace
cors:
  allowed:
    origins: "${CORS_ALLOWED}"

